[package]
name = "ultra_simple"
version = "0.6.0"
authors = ["Tony Huang <tony@slamtec.com>"]
edition = "2018"

[dependencies]
rplidar_drv = { path = "../.." }
rpos_drv = { path = "../../rpos_drv" }
hex-slice = "0.1.4"
plotters = "0.3.1"
